// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdh5oIgl_uMJmjBtGIKHslo0KLi822p10',
    appId: '1:409022677678:web:ce379497e00fd78d41633f',
    messagingSenderId: '409022677678',
    projectId: 'srs-flashcard-dp',
    authDomain: 'srs-flashcard-dp.firebaseapp.com',
    storageBucket: 'srs-flashcard-dp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiRXXj-iMSXW5WAmUNqit1Rw3Cmf0lIq4',
    appId: '1:409022677678:android:0bff2c6ae049a69e41633f',
    messagingSenderId: '409022677678',
    projectId: 'srs-flashcard-dp',
    storageBucket: 'srs-flashcard-dp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIdXCz0DLUQ2b1MptruYdESEnhF94OSg',
    appId: '1:409022677678:ios:4f974d1958f0d6e441633f',
    messagingSenderId: '409022677678',
    projectId: 'srs-flashcard-dp',
    storageBucket: 'srs-flashcard-dp.firebasestorage.app',
    iosBundleId: 'com.example.srsapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGIdXCz0DLUQ2b1MptruYdESEnhF94OSg',
    appId: '1:409022677678:ios:4f974d1958f0d6e441633f',
    messagingSenderId: '409022677678',
    projectId: 'srs-flashcard-dp',
    storageBucket: 'srs-flashcard-dp.firebasestorage.app',
    iosBundleId: 'com.example.srsapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdh5oIgl_uMJmjBtGIKHslo0KLi822p10',
    appId: '1:409022677678:web:a8c8daec2d848b0f41633f',
    messagingSenderId: '409022677678',
    projectId: 'srs-flashcard-dp',
    authDomain: 'srs-flashcard-dp.firebaseapp.com',
    storageBucket: 'srs-flashcard-dp.firebasestorage.app',
  );
}
